<a href="https://colab.research.google.com/github/Akashgola123/Computer_vision_with_Tensorflow/blob/main/Tensorflow_computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORS are multi dimension array


An Array is an order arragement of Numbers

In [1]:
# initialization and casting

import tensorflow as tf


In [ ]:
tensor_zero_dt = tf.constant(4)
print(tensor_zero_dt)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_dt = tf.constant([2,0,-3],dtype=tf.int32)
cast_tensor_dt = tf.cast(tensor_one_dt,dtype=tf.bool)
print(tensor_one_dt)
print(cast_tensor_dt)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
tensor_two_dt = tf.constant([[4, -2, 5], [-3, 7, -0],[4,9,3],[2,7,8]])
print(tensor_two_dt)

tf.Tensor(
[[ 4 -2  5]
 [-3  7  0]
 [ 4  9  3]
 [ 2  7  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_dt = tf.constant([[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]])
print(tensor_three_dt)

tf.Tensor(
[[[ 4 -2  5]
  [-3  7  0]]

 [[ 4  9  3]
  [ 2  7  8]]

 [[ 4 -2  5]
  [-3  7  0]]

 [[ 4  6  7]
  [ 9  0  5]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_dt.shape)
print(tensor_three_dt.ndim)
print(tensor_three_dt.dtype)
print(tf.size(tensor_three_dt))

(4, 2, 3)
3
<dtype: 'int32'>
tf.Tensor(24, shape=(), dtype=int32)


In [ ]:
[[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]]

tf.Tensor(
[[[ 4. -2.  5.]
  [-3.  7.  0.]]

 [[ 4.  9.  3.]
  [ 2.  7.  8.]]

 [[ 4. -2.  5.]
  [-3.  7.  0.]]

 [[ 4.  6.  7.]
  [ 9.  0.  5.]]], shape=(4, 2, 3), dtype=float16)


In [ ]:
tf_four_dt = tf.constant([[[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]],[[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]],[[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]],[[[4, -2, 5], [-3, 7, -0]],[[4,9,3],[2,7,8]],[[4, -2, 5], [-3, 7, -0]],[[4,6,7],[9,0,5]]]])
print(tf_four_dt)

tf.Tensor(
[[[[ 4 -2  5]
   [-3  7  0]]

  [[ 4  9  3]
   [ 2  7  8]]

  [[ 4 -2  5]
   [-3  7  0]]

  [[ 4  6  7]
   [ 9  0  5]]]


 [[[ 4 -2  5]
   [-3  7  0]]

  [[ 4  9  3]
   [ 2  7  8]]

  [[ 4 -2  5]
   [-3  7  0]]

  [[ 4  6  7]
   [ 9  0  5]]]


 [[[ 4 -2  5]
   [-3  7  0]]

  [[ 4  9  3]
   [ 2  7  8]]

  [[ 4 -2  5]
   [-3  7  0]]

  [[ 4  6  7]
   [ 9  0  5]]]


 [[[ 4 -2  5]
   [-3  7  0]]

  [[ 4  9  3]
   [ 2  7  8]]

  [[ 4 -2  5]
   [-3  7  0]]

  [[ 4  6  7]
   [ 9  0  5]]]], shape=(4, 4, 2, 3), dtype=int32)


In [ ]:
print(tf_four_dt.shape)
print(tf_four_dt.ndim)
print(tf_four_dt.dtype)
print(tf.size(tf_four_dt))

(4, 4, 2, 3)
4
<dtype: 'int32'>
tf.Tensor(96, shape=(), dtype=int32)


In [ ]:
import numpy as np


In [ ]:
np_array_list = np.array([1,2,3,4])
print(np_array_list.ndim)

1


In [ ]:
convert_tf_to_np = tf.convert_to_tensor(np_array_list)
print(convert_tf_to_np)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


Eye Method is a Construct an identity matrix, or a batch of matrices.

In [ ]:
tensor_matrix = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,3],
    dtype=tf.dtypes.int32,
    name=None
)
print(5*tensor_matrix)

tf.Tensor(
[[[[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]

  [[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]

  [[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]]


 [[[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]

  [[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]

  [[5 0 0 0 0]
   [0 5 0 0 0]
   [0 0 5 0 0]
   [0 0 0 5 0]
   [0 0 0 0 5]]]], shape=(2, 3, 5, 5), dtype=int32)


Creates a tensor filled with a scalar value.

In [ ]:
tensor_fill = tf.fill(
    [2,4,5],7,name=None
)
print(tensor_fill)

tf.Tensor(
[[[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]], shape=(2, 4, 5), dtype=int32)


Creates a tensor with all elements set to one (1).

In [ ]:
tensor_ones = tf.ones(
    shape=[5,3,4,5],
    dtype=tf.dtypes.int32,
    name=None,
    layout=None
)
print(tensor_ones)

tf.Tensor(
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]], shape=(5, 3, 4, 5), dtype=int32)


Creates a tensor of all ones that has the same shape as the input.

In [ ]:
ones_tensor = tf.ones_like(
    [[2,3,4],[4,5,3]], dtype=None, name=None, layout=None
)
print(ones_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


Creates a tensor with all elements set to zero.

In [ ]:
zero_tensor = tf.zeros(
    shape=[5,3,4,5],
    dtype=tf.dtypes.int32,
    name=None,
    layout=None
)
print(zero_tensor)

tf.Tensor(
[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]], shape=(5, 3, 4, 5), dtype=int32)


Returns the rank of a tensor.

In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Outputs random values from a normal distribution.

In [ ]:
radam_tensor = tf.random.normal(
    shape=[3,3],
    mean=10.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(radam_tensor)

tf.Tensor(
[[10.078788   9.9012785  9.436123 ]
 [10.127979  10.332671   8.321602 ]
 [ 8.618841   9.417417  11.983002 ]], shape=(3, 3), dtype=float32)


Maths function ..

Asihn function


In [ ]:
X_no = tf.constant([-2.70,-1.50])
print(abs(X_no))

tf.Tensor([2.7 1.5], shape=(2,), dtype=float32)


In [ ]:
x_abs_complex = tf.constant([-2.70+4.80j])
print(tf.abs(x_abs_complex))

tf.Tensor([5.50726793], shape=(1,), dtype=float64)


it function working at index of the maximum number then return the index of max nukmber

In [ ]:
X_argmax = tf.constant([2,1,4,3])
print(tf.argmax(X_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
input = tf.constant([[1, 2], [3, 4]])

x_topk=tf.math.top_k(
    input,
    k=1,
    sorted=True,
    index_type=tf.dtypes.int32,
    name=None
)
print(x_topk)

TopKV2(values=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [4]], dtype=int32)>, indices=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [1]], dtype=int32)>)


Linaer Alegbra :-
1. Multiplies matrix a by matrix b, producing a * b.

In [2]:
x_matmul = tf.constant([[1, 2], [3, 4]])
y_matmul = tf.constant([[5, 6], [7, 8]])
print(tf.matmul(x_matmul,y_matmul))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [3]:
tf.linalg.matmul(
    x_matmul,
    y_matmul,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [4]:
print(x_matmul@y_matmul)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
